import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    width: 140,
    height: 140,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  // Capacete
  helmet: {
    width: 100,
    height: 90,
    backgroundColor: '#FF6B35',
    borderRadius: 50,
    borderBottomLeftRadius: 20,
    borderBottomRightRadius: 20,
    position: 'relative',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  helmetTop: {
    position: 'absolute',
    top: -10,
    left: 20,
    right: 20,
    height: 30,
    backgroundColor: '#FF8C5F',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
  },
  helmetVisor: {
    position: 'absolute',
    bottom: 15,
    left: 10,
    right: 10,
    height: 25,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#FFB800',
  },
  helmetBadge: {
    position: 'absolute',
    bottom: 45,
    left: 35,
    width: 30,
    height: 30,
    backgroundColor: '#FFB800',
    borderRadius: 15,
    borderWidth: 2,
    borderColor: '#fff',
  },
  badgeShine: {
    position: 'absolute',
    top: 4,
    left: 4,
    width: 10,
    height: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 5,
  },
  // Emblema inferior
  emblem: {
    marginTop: 10,
    width: 50,
    height: 50,
    backgroundColor: '#1a1f3a',
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: '#FF6B35',
  },
  emblemInner: {
    width: 25,
    height: 25,
    backgroundColor: '#FF6B35',
    borderRadius: 12.5,
  },
  // Círculos decorativos
  decorativeCircle1: {
    position: 'absolute',
    top: 10,
    right: 5,
    width: 15,
    height: 15,
    backgroundColor: 'rgba(255, 107, 53, 0.3)',
    borderRadius: 7.5,
  },
  decorativeCircle2: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    width: 20,
    height: 20,
    backgroundColor: 'rgba(255, 184, 0, 0.3)',
    borderRadius: 10,
  },
  decorativeCircle3: {
    position: 'absolute',
    top: 50,
    left: 10,
    width: 12,
    height: 12,
    backgroundColor: 'rgba(255, 107, 53, 0.4)',
    borderRadius: 6,
  },
});
